#!/usr/bin/env bash
# scripts/bootstrap-docker.sh — zero-to-running-service in one command.
#
# Usage from a fresh git clone:
#
#   git clone https://github.com/vampir15551/skr-crypto.git
#   cd skr-crypto
#   ./scripts/bootstrap-docker.sh
#
# What it does:
#   1. Verifies Docker is installed and the daemon is running.
#   2. Generates fresh AUTH_TOKEN, KEY_PASSPHRASE, WEBHOOK_SIGNING_SECRET.
#   3. Builds the image and uses it to initialise an encrypted keystore
#      with one freshly-generated wallet ("main"). NO Python required
#      on the host — everything runs inside the container.
#   4. Writes .env with safe local-dev defaults (chmod 600).
#   5. Starts the service via docker compose up -d.
#   6. Waits for /health/live, prints summary + the AUTH_TOKEN to use.
#
# Re-run with BOOTSTRAP_FORCE=1 to wipe and re-init from scratch.

set -euo pipefail

# Resolve repo root regardless of where the script is called from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# ── 0. Pretty output helpers ─────────────────────────────────────────
RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'
BOLD=$'\033[1m'; RESET=$'\033[0m'
say()  { printf "%s→%s %s\n" "$BLUE" "$RESET" "$*"; }
ok()   { printf "%s✓%s %s\n" "$GREEN" "$RESET" "$*"; }
warn() { printf "%s⚠%s %s\n" "$YELLOW" "$RESET" "$*"; }
die()  { printf "%s✗%s %s\n" "$RED" "$RESET" "$*" >&2; exit 1; }

# ── 1. Pre-flight checks ─────────────────────────────────────────────
say "Pre-flight checks..."

if ! command -v docker >/dev/null 2>&1; then
    die "docker not found. Install Docker Desktop:
       https://www.docker.com/products/docker-desktop"
fi

# Detect docker compose v2 (preferred) vs legacy docker-compose v1.
if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
    warn "Using legacy docker-compose v1. Consider upgrading to Docker Desktop / Compose v2."
else
    die "Neither 'docker compose' nor 'docker-compose' is available."
fi

if ! docker info >/dev/null 2>&1; then
    die "Docker daemon is not running. Start Docker Desktop and re-run."
fi

if [ -f .env ] && [ -z "${BOOTSTRAP_FORCE:-}" ]; then
    die ".env already exists — refusing to overwrite.
       Re-run with BOOTSTRAP_FORCE=1 to wipe + re-init from scratch,
       or '$DC up -d' to just start with the existing config."
fi

if [ -n "${BOOTSTRAP_FORCE:-}" ]; then
    warn "BOOTSTRAP_FORCE=1 — wiping ./data and ./.env"
    $DC down --volumes 2>/dev/null || true
    rm -rf data .env
fi

ok "Docker ($($DC version --short 2>/dev/null || echo "found")) is running"

# ── 2. Generate secrets ──────────────────────────────────────────────
say "Generating fresh secrets..."

# Use openssl if available; fall back to /dev/urandom for portability.
gen_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | xxd -p -c 64
    fi
}

AUTH_TOKEN=$(gen_hex)
KEY_PASSPHRASE=$(gen_hex)
WEBHOOK_SECRET=$(gen_hex)

ok "Generated AUTH_TOKEN, KEY_PASSPHRASE, WEBHOOK_SIGNING_SECRET"

# ── 3. Write .env ────────────────────────────────────────────────────
say "Writing .env..."

mkdir -p data
cat > .env <<EOF
# =============================================================================
#  Generated by scripts/bootstrap-docker.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#  Local-dev / single-host deploy via docker-compose.yml
# =============================================================================

# --- Auth (legacy single-token; mint scoped tokens later via
#     '$DC exec skr-crypto skr-crypto token create ...') ---
AUTH_TOKEN=$AUTH_TOKEN

# --- Key provider: encrypted_file (multi-wallet, container-safe) ---
KEY_PROVIDER=encrypted_file
KEYSTORE_FILE=/var/lib/skr-crypto/data/keystore.json
KEY_PASSPHRASE=$KEY_PASSPHRASE

# --- TRON network ---
TRON_NETWORK=mainnet
TRONGRID_API_KEY=
USDT_CONTRACT=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
USDT_FEE_LIMIT_SUN=30000000
MIN_TRX_RESERVE=50

# --- Cost controls ---
MAX_ENERGY_BURN_TRX=20

# --- Risk preflight (always on; TronScan adds ~300ms per /send) ---
RISK_BLOCK_LEVEL=high
RISK_USE_EXTERNAL=true

# --- OFAC SDN sanctions (always on, no rate limit) ---
SANCTIONS_LIST_REFRESH=true

# --- Audit (durable JSON-line, fsync per record) ---
AUDIT_LOG_FILE=data/audit.log

# --- Idempotency (SQLite WAL, persists across restarts) ---
IDEMPOTENCY_DB_PATH=data/idempotency.db

# --- Server (override SERVER_HOST=0.0.0.0 in compose for container access) ---
SERVER_HOST=127.0.0.1
SERVER_PORT=8000
SHUTDOWN_TIMEOUT=31536000

# --- Rate limiting (token-bucket, persistent) ---
RATE_LIMIT_IP_CAPACITY=30
RATE_LIMIT_IP_REFILL_PER_SEC=0.5
RATE_LIMIT_TOKEN_CAPACITY=100
RATE_LIMIT_TOKEN_REFILL_PER_SEC=2.0

# --- Receipt poller (postmortem-only; never retries) ---
RECEIPT_POLL_INTERVAL_SEC=60
RECEIPT_LOOKBACK_HOURS=48

# --- Webhooks (off by default; uncomment WEBHOOK_URLS to enable) ---
# WEBHOOK_URLS=https://your-webhook.example.com/skr
WEBHOOK_SIGNING_SECRET=$WEBHOOK_SECRET
EOF
chmod 600 .env

ok "wrote .env (chmod 600)"

# ── 4. Build the Docker image ────────────────────────────────────────
say "Building Docker image (first build ~1-2min)..."
$DC build skr-crypto 2>&1 | tail -3 || die "image build failed"
ok "image built"

# ── 5. Initialise the encrypted keystore + first wallet ──────────────
# We use 'docker compose run --rm --entrypoint skr-crypto' to invoke the
# CLI inside the same image that runs the service. The keystore lands
# in the bind-mounted data/ volume, so the running service will see it.
#
# We override the entrypoint because the Dockerfile's default is
# 'skr-crypto-server' (the FastAPI process); we want the CLI here.

say "Initialising encrypted keystore..."
$DC run --rm --no-deps \
    -e KEY_PASSPHRASE="$KEY_PASSPHRASE" \
    --entrypoint skr-crypto \
    skr-crypto \
    wallet encrypt \
        -o /var/lib/skr-crypto/data/keystore.json \
        --force \
    > /tmp/skr-bootstrap-encrypt.log 2>&1 \
    || { tail /tmp/skr-bootstrap-encrypt.log; die "wallet encrypt failed"; }
ok "keystore initialised at data/keystore.json"

say "Generating wallet 'main' inside the keystore..."
$DC run --rm --no-deps \
    -e KEY_PASSPHRASE="$KEY_PASSPHRASE" \
    --entrypoint skr-crypto \
    skr-crypto \
    wallet generate main --yes \
    > /tmp/skr-bootstrap-gen.log 2>&1 \
    || { tail /tmp/skr-bootstrap-gen.log; die "wallet generate failed"; }

# Pull the address out of the bootstrap log so we can print it in the summary.
WALLET_ADDR=$(grep -oE 'T[A-HJ-NP-Za-km-z1-9]{33}' /tmp/skr-bootstrap-gen.log | head -1 || true)
ok "wallet 'main' generated: ${WALLET_ADDR:-(see logs)}"

# ── 6. Start the service ─────────────────────────────────────────────
say "Starting the service..."
$DC up -d skr-crypto >/dev/null
ok "service started"

# ── 7. Wait for /health/live ─────────────────────────────────────────
say "Waiting for /health/live to respond..."
HEALTHY=0
for i in $(seq 1 60); do
    if curl -s -f http://127.0.0.1:8000/api/v1/health/live >/dev/null 2>&1; then
        HEALTHY=1
        break
    fi
    sleep 1
done

if [ "$HEALTHY" -ne 1 ]; then
    warn "service didn't respond on /health/live within 60s"
    warn "check logs:  $DC logs skr-crypto"
    exit 1
fi
ok "service is healthy"

# ── 8. Summary ───────────────────────────────────────────────────────
cat <<EOF

${BOLD}══════════════════════════════════════════════════════════════════════${RESET}
${GREEN}${BOLD}✓ skr-crypto is running${RESET}
${BOLD}══════════════════════════════════════════════════════════════════════${RESET}

${BOLD}Operator UI:${RESET}    http://127.0.0.1:8000/ui/
                Paste this token at the prompt:

                ${YELLOW}${AUTH_TOKEN}${RESET}

${BOLD}API base:${RESET}       http://127.0.0.1:8000/api/v1/
${BOLD}Health probe:${RESET}   http://127.0.0.1:8000/api/v1/health/live
${BOLD}Wallet 'main':${RESET}  ${WALLET_ADDR:-(check 'skr-crypto wallet list' inside container)}
                ↑ fund this address with TRX (≥50 for fees) + USDT to test.

${BOLD}Send a transfer:${RESET}
  curl -X POST http://127.0.0.1:8000/api/v1/send \\
       -H "X-API-Key: ${AUTH_TOKEN}" \\
       -H "Content-Type: application/json" \\
       -d '{"to_address":"<recipient-T-address>",
            "amount":"1.0",
            "idempotency_key":"first-test"}'

${BOLD}Common commands:${RESET}
  $DC logs -f skr-crypto                     # tail logs
  $DC exec skr-crypto skr-crypto wallet list # list wallets
  $DC exec skr-crypto skr-crypto balance     # treasury balance
  $DC exec skr-crypto skr-crypto audit       # audit log
  $DC exec skr-crypto skr-crypto token list  # API tokens
  $DC restart skr-crypto                     # restart service
  $DC down                                   # stop service

${BOLD}Files to back up:${RESET}
  ./.env                  AUTH_TOKEN + KEY_PASSPHRASE
  ./data/keystore.json    AES-256-GCM encrypted private keys
  ./data/audit.log        financial trail (append-only)
  ./data/idempotency.db   replay protection state

${BOLD}${RED}Lose the passphrase = lose the keys.${RESET} There is no recovery.

${BOLD}══════════════════════════════════════════════════════════════════════${RESET}
EOF
